sudo: true

services:
  - docker

language: python

env:
  global:
    - secure:  # DOCKER_EMAIL
    - secure:  # DOCKER_USER
    - secure:  # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::8}
    - LANG="C.UTF-8"
    - LC_ALL="C"
    # temp. limit what is build on each commit to speed up testing
    - DIST=ubuntu
    - DIST_REL=xenial
    - SALT=stable
    - FORMULA_REV=nightly
  matrix:
    - TARGET=wheelhouse
    #- TARGET=saltstack
    #- TARGET=saltmaster
    #- TARGET=saltmaster-reclass
    #- TARGET=saltmaster-saltclass SALT=develop

install:
  - pip install -e "git+https://github.com/avirshup/DockerMake#egg=dockermake"
  - pip install -e "git+https://github.com/pyinvoke/invoke#egg=invoke"

script:
  # TODO, docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export PUSH=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "--push"; fi`
  # Test first
  - invoke all --dry-targets --filter "{'target':'"$TARGET"', 'salt':'"$SALT"', 'dist':'"$DIST"', 'dist_rel':'"$DIST_REL"', 'formula_rev':'"$FORMULA_REV"'}" #$PUSH
  - invoke all --dry         --filter "{'target':'"$TARGET"', 'salt':'"$SALT"', 'dist':'"$DIST"', 'dist_rel':'"$DIST_REL"', 'formula_rev':'"$FORMULA_REV"'}" #$PUSH
  # TODO, write proper parallel flow
  - invoke all --filter "{'target':'"$TARGET"', 'salt':'"$SALT"', 'dist':'"$DIST"', 'dist_rel':'"$DIST_REL"', 'formula_rev':'"$FORMULA_REV"'}" #$PUSH

# after_success:
#  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
#  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo ""; else echo "-$TRAVIS_BRANCH" ; fi`
  # PUSH ALL BUILD IMAGES to Docker hub
    #- docker tag $REPO:$COMMIT $REPO:$TAG
    #- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    #- docker push $REPO

after_failure:
  - cat dockerfile.fail

# TODO, notify
