sudo: true

services:
- docker

language: python

cache: pip

python:
- '3.6'

env:
  global:
  #- LANG="C.UTF-8"
  #- LC_ALL="C"
  - LC_ALL=en_US.UTF-8
  - LANG=en_US.UTF-8
  - FORMULA_REV=nightly
  - PIPENV_SHELL_COMPAT=true PIPENV_COLORBLIND=true PIPENV_NOSPIN=true
  - COMMIT=${TRAVIS_COMMIT::8}
  # DOCKERHUB CI UPLOAD OVER TRAVIS IS NOT USED
  # DOCKER_USER:
  #- secure: REMOVED
  # DOCKER_PASS:
  #- secure: REMOVED
  matrix:
  - DIST=ubuntu
  - DIST=debian TARGET=saltstack
  - DIST=centos TARGET=saltstack
  # TODO, replace two above ^^ once saltmaster target is passing on all platforms
  #- DIST=debian
  #- DIST=centos

install:
#- pip install pipenv
#- pipenv install --three
- pip install -e "git+https://github.com/avirshup/DockerMake#egg=dockermake"
- pip install -e "git+https://github.com/pyinvoke/invoke#egg=invoke"

script:
- invoke all --dry-targets --filter "{'target':'"$TARGET"', 'salt':'"$SALT"', 'dist':'"$DIST"',
  'dist_rel':'"$DIST_REL"', 'formula_rev':'"$FORMULA_REV"'}"
- invoke all --dry         --filter "{'target':'"$TARGET"', 'salt':'"$SALT"', 'dist':'"$DIST"',
  'dist_rel':'"$DIST_REL"', 'formula_rev':'"$FORMULA_REV"'}"
# 1st build (build/test)
- invoke all --filter "{'target':'"$TARGET"', 'salt':'"$SALT"', 'dist':'"$DIST"',
  'dist_rel':'"$DIST_REL"', 'formula_rev':'"$FORMULA_REV"'}"
# 2nd build (push, with cached artefacts)
- if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    echo $DOCKER_PASS | docker login --password-stdin -u $DOCKER_USER docker.io/epcim/salt;
    export PUSH="--push";
    invoke all --filter "{'target':'"$TARGET"', 'salt':'"$SALT"', 'dist':'"$DIST"', 'dist_rel':'"$DIST_REL"', 'formula_rev':'"$FORMULA_REV"'}" $PUSH ;
  fi

after_failure:
- test -e dockerfile.fail && cat dockerfile.fail || true

after_success:
- docker images
